//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodsAccountingPractice1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceGoodsList = new HashSet<InvoiceGoodsList>();
        }
    
        public int IdInvoice { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<int> IdSuppliers { get; set; }
        public Nullable<int> IdUsers { get; set; }
        public Nullable<bool> Cofirmation { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceGoodsList> InvoiceGoodsList { get; set; }
    }
}
