//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodsAccountingPractice1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceGoodsList
    {
        public int IdList { get; set; }
        public int IdInvoice { get; set; }
        public int IdProduct { get; set; }
        public string AmountProduct { get; set; }
    
        public virtual GoodsDirectory GoodsDirectory { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
